{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.dockerCredentials.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "flyerss.fullname" . }}-docker-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    {{- if .Values.externalSecrets.clusterSecretStore }}
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStore }}
    {{- end }}
  target:
    name: {{ include "flyerss.fullname" . }}-registry-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"{{ .Values.externalSecrets.dockerCredentials.registry }}":{"username":"{{ .Values.externalSecrets.dockerCredentials.username }}","password":"{{ "{{ .password }}" }}","auth":"{{ "{{ printf \"%s:%s\" \"" }}{{ .Values.externalSecrets.dockerCredentials.username }}{{ "\" .password | b64enc }}" }}"}}}
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.dockerCredentials.passwordKey }}
{{- end }}
