{{- if and .Values.externalSecrets.enabled (gt (len .Values.externalSecrets.env) 0) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "flyerss.fullname" . }}-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    {{- if .Values.externalSecrets.clusterSecretStore }}
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStore }}
    {{- end }}
  target:
    name: {{ include "flyerss.fullname" . }}-secret
  data:
    {{- range .Values.externalSecrets.env }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .remoteKey }}
    {{- end }}
{{- end }}
