{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flyerss.serviceAccountName" . }}
  labels:
    {{- include "flyerss.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- if .Values.externalSecrets.dockerCredentials.enabled }}
imagePullSecrets:
  - name: {{ include "flyerss.fullname" . }}-registry-secret
{{- end }}
{{- end }}
